//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coil_Diagnostor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("한빛 1발전소")]
        public string PlantName {
            get {
                return ((string)(this["PlantName"]));
            }
            set {
                this["PlantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 호기,2 호기")]
        public string HogiData {
            get {
                return ((string)(this["HogiData"]));
            }
            set {
                this["HogiData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB0::0x0957::0x0909::MY54203641::INSTR")]
        public string LCRMeter_Addr {
            get {
                return ((string)(this["LCRMeter_Addr"]));
            }
            set {
                this["LCRMeter_Addr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Agilent Technologies,E4980AL,MY54202736,A.06.15")]
        public string LCRMeter_ID {
            get {
                return ((string)(this["LCRMeter_ID"]));
            }
            set {
                this["LCRMeter_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.103")]
        public string TDRMeter_IPAddress {
            get {
                return ((string)(this["TDRMeter_IPAddress"]));
            }
            set {
                this["TDRMeter_IPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55556")]
        public string TDRMeter_IPPort {
            get {
                return ((string)(this["TDRMeter_IPPort"]));
            }
            set {
                this["TDRMeter_IPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev1")]
        public string DAQDeviceName {
            get {
                return ((string)(this["DAQDeviceName"]));
            }
            set {
                this["DAQDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21")]
        public string Control_Item {
            get {
                return ((string)(this["Control_Item"]));
            }
            set {
                this["Control_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1,A2,A3,A4,A5,A6,A18,A19,A20,A21")]
        public string Stop_Item {
            get {
                return ((string)(this["Stop_Item"]));
            }
            set {
                this["Stop_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal RdcDecisionRange_ReferenceValue {
            get {
                return ((decimal)(this["RdcDecisionRange_ReferenceValue"]));
            }
            set {
                this["RdcDecisionRange_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal RacDecisionRange_ReferenceValue {
            get {
                return ((decimal)(this["RacDecisionRange_ReferenceValue"]));
            }
            set {
                this["RacDecisionRange_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal LDecisionRange_ReferenceValue {
            get {
                return ((decimal)(this["LDecisionRange_ReferenceValue"]));
            }
            set {
                this["LDecisionRange_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal CDecisionRange_ReferenceValue {
            get {
                return ((decimal)(this["CDecisionRange_ReferenceValue"]));
            }
            set {
                this["CDecisionRange_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal QDecisionRange_ReferenceValue {
            get {
                return ((decimal)(this["QDecisionRange_ReferenceValue"]));
            }
            set {
                this["QDecisionRange_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal EffectiveStandardRangeOfVariation {
            get {
                return ((decimal)(this["EffectiveStandardRangeOfVariation"]));
            }
            set {
                this["EffectiveStandardRangeOfVariation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WheatstoneDataNumber {
            get {
                return ((int)(this["WheatstoneDataNumber"]));
            }
            set {
                this["WheatstoneDataNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.00")]
        public decimal Temperature_ReferenceValue {
            get {
                return ((decimal)(this["Temperature_ReferenceValue"]));
            }
            set {
                this["Temperature_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public decimal TemperatureUpDown_ReferenceValue {
            get {
                return ((decimal)(this["TemperatureUpDown_ReferenceValue"]));
            }
            set {
                this["TemperatureUpDown_ReferenceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("제어용,정지용")]
        public string DRPIReferenceValueLabelType {
            get {
                return ((string)(this["DRPIReferenceValueLabelType"]));
            }
            set {
                this["DRPIReferenceValueLabelType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1,A2,B1,B2,A3 ~ 21,B3 ~ 21")]
        public string DRPIReferenceValueLabelControlName {
            get {
                return ((string)(this["DRPIReferenceValueLabelControlName"]));
            }
            set {
                this["DRPIReferenceValueLabelControlName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1/A2/B1/B2/A3~6,18~21/B3~6,18~21")]
        public string DRPIReferenceValueLabelStopName {
            get {
                return ((string)(this["DRPIReferenceValueLabelStopName"]));
            }
            set {
                this["DRPIReferenceValueLabelStopName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 1,DAM 2,DAM 3,DAM 4,DAM 5,DAM 6,DAM 7,DAM 8,DAM 9,DAM 10")]
        public string DAMRelayItem {
            get {
                return ((string)(this["DAMRelayItem"]));
            }
            set {
                this["DAMRelayItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100 Hz,120 Hz,1 kHz,10 kHz,100 kHz")]
        public string FrequencyItem {
            get {
                return ((string)(this["FrequencyItem"]));
            }
            set {
                this["FrequencyItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"2000mV,1950mV,1900mV,1850mV,1800mV,1750mV,1700mV,1650mV,1600mV,1550mV,1500mV,1450mV,1400mV,1350mV,1300mV,1250mV,1200mV,1150mV,1100mV,1050mV,1000mV,950mV,900mV,850mV,800mV,750mV,700mV,650mV,600mV,550mV,500mV,450mV,400mV,350mV,300mV,250mV,200mV,150mV,100mV,50mV,20mV")]
        public string VoltageLevelItem {
            get {
                return ((string)(this["VoltageLevelItem"]));
            }
            set {
                this["VoltageLevelItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 회,2 회,3 회,4 회,5 회,6 회,7 회,8 회,9 회,10 회")]
        public string MeasurementCountItem {
            get {
                return ((string)(this["MeasurementCountItem"]));
            }
            set {
                this["MeasurementCountItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2,B10,K14,P6,D4,D12,M12,M4,G3,C9,J13,N7")]
        public string RCSPowerCabinetItem_1AC {
            get {
                return ((string)(this["RCSPowerCabinetItem_1AC"]));
            }
            set {
                this["RCSPowerCabinetItem_1AC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K2,B6,F14,P10,H6,F8,H10,K8,J3,C7,G13,N9")]
        public string RCSPowerCabinetItem_2AC {
            get {
                return ((string)(this["RCSPowerCabinetItem_2AC"]));
            }
            set {
                this["RCSPowerCabinetItem_2AC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4,D10,K12,M6,H2,H14,E5,E11,L11,L5,N/A,N/A")]
        public string RCSPowerCabinetItem_1BD {
            get {
                return ((string)(this["RCSPowerCabinetItem_1BD"]));
            }
            set {
                this["RCSPowerCabinetItem_1BD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K4,D6,F12,M10,B8,P8,G7,G9,J9,J7,N/A,N/A")]
        public string RCSPowerCabinetItem_2BD {
            get {
                return ((string)(this["RCSPowerCabinetItem_2BD"]));
            }
            set {
                this["RCSPowerCabinetItem_2BD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E3,C11,L13,N5,F6,F10,K10,K6,N/A,N/A,N/A,N/A\r\n")]
        public string RCSPowerCabinetItem_SCD {
            get {
                return ((string)(this["RCSPowerCabinetItem_SCD"]));
            }
            set {
                this["RCSPowerCabinetItem_SCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G3,C9,J13,N7,J3,C7/없음")]
        public string DRPIButtonCardFrame1 {
            get {
                return ((string)(this["DRPIButtonCardFrame1"]));
            }
            set {
                this["DRPIButtonCardFrame1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G13,N9,E5,E11,L11,L5,G7,G9,J9,J7/없음")]
        public string DRPIButtonCardFrame2 {
            get {
                return ((string)(this["DRPIButtonCardFrame2"]));
            }
            set {
                this["DRPIButtonCardFrame2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E3,C11,L13/없음")]
        public string DRPIButtonCardFrame2_1 {
            get {
                return ((string)(this["DRPIButtonCardFrame2_1"]));
            }
            set {
                this["DRPIButtonCardFrame2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N5,F6,F10,K10,K6,F2,B10,K14,P6,K2")]
        public string DRPIButtonCardFrame3 {
            get {
                return ((string)(this["DRPIButtonCardFrame3"]));
            }
            set {
                this["DRPIButtonCardFrame3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음/B6,F14")]
        public string DRPIButtonCardFrame3_1 {
            get {
                return ((string)(this["DRPIButtonCardFrame3_1"]));
            }
            set {
                this["DRPIButtonCardFrame3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음/P10,F4,D10,K12,M6,K4,D6,F12,M10,D4")]
        public string DRPIButtonCardFrame4 {
            get {
                return ((string)(this["DRPIButtonCardFrame4"]));
            }
            set {
                this["DRPIButtonCardFrame4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음/D12,M12,M4,H6")]
        public string DRPIButtonCardFrame4_1 {
            get {
                return ((string)(this["DRPIButtonCardFrame4_1"]));
            }
            set {
                this["DRPIButtonCardFrame4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("없음/F8,H10,K8,H2,H14,B8,P8")]
        public string DRPIButtonCardFrame5 {
            get {
                return ((string)(this["DRPIButtonCardFrame5"]));
            }
            set {
                this["DRPIButtonCardFrame5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,3,4,5,6,18,19,20,21")]
        public string DRPIStopCoilName_Item {
            get {
                return ((string)(this["DRPIStopCoilName_Item"]));
            }
            set {
                this["DRPIStopCoilName_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21")]
        public string DRPIControlCoilName_Item {
            get {
                return ((string)(this["DRPIControlCoilName_Item"]));
            }
            set {
                this["DRPIControlCoilName_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("정지,올림,이동")]
        public string RCSCoilName_Item {
            get {
                return ((string)(this["RCSCoilName_Item"]));
            }
            set {
                this["RCSCoilName_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("평균치,측정치")]
        public string RCSType_Item {
            get {
                return ((string)(this["RCSType_Item"]));
            }
            set {
                this["RCSType_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("기준값,평균값")]
        public string ComparisonTarget_Item {
            get {
                return ((string)(this["ComparisonTarget_Item"]));
            }
            set {
                this["ComparisonTarget_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("주기별,기간별")]
        public string HistorySearchType_Item {
            get {
                return ((string)(this["HistorySearchType_Item"]));
            }
            set {
                this["HistorySearchType_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1AC,2AC,1BD,2BD,SCD")]
        public string RCSMeasurementGroup_Item {
            get {
                return ((string)(this["RCSMeasurementGroup_Item"]));
            }
            set {
                this["RCSMeasurementGroup_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"없음,Slot 선택,Power Voltage 설정,Power OCP 설정,Power On/Off,DMM Mode 설정,DMM Range 설정,Delay,DMM Voltage ArrayRead,DMM Current ArrayRead,DMM Voltage Read,DMM Current Read,Relay On,Relay Off,Load Relay On,Load Relay Off,결과 값,결과 판정(이내),결과 판정(이하),결과 판정(이상),그래프 취득,Aging 그래프 취득")]
        public string SettingType {
            get {
                return ((string)(this["SettingType"]));
            }
            set {
                this["SettingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Block 1 Input Stage Drop Test,Block 1 Outpur Stage Drop Test,Block 1 Output Stage Leakage Test,Block 1 Function Test,Block 1 Photocoupler Deterioration Test,Block 2 Input Stage Drop Test,Block 2 Outpur Stage Drop Test,Block 2 Output Stage Leakage Test,Block 2 Function Test,Block 2 Photocoupler Deterioration Test,Block 1 Aging Test,Block 2 Aging Test,Block All Aging Test")]
        public string Measurement_Item {
            get {
                return ((string)(this["Measurement_Item"]));
            }
            set {
                this["Measurement_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A,B")]
        public string DRPIGroup_Item {
            get {
                return ((string)(this["DRPIGroup_Item"]));
            }
            set {
                this["DRPIGroup_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2,B10,K14,P6,K2,B6,F14,P10,F4,D10,K12,M6,K4,D6,F12,M10,D4,D12,M12,M4,H6,F8,H10,K" +
            "8,H2,H14,B8,P8")]
        public string DRPIControlRodColilName_Item {
            get {
                return ((string)(this["DRPIControlRodColilName_Item"]));
            }
            set {
                this["DRPIControlRodColilName_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G3,C9,J13,N7,J3,C7,G13,N9,E5,E11,L11,L5,G7,G9,J9,J7,E3,C11,L13,N5,F6,F10,K10,K6")]
        public string DRPIControlRodStopName_Item {
            get {
                return ((string)(this["DRPIControlRodStopName_Item"]));
            }
            set {
                this["DRPIControlRodStopName_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line22")]
        public string OPROnOff_DAQPinMap {
            get {
                return ((string)(this["OPROnOff_DAQPinMap"]));
            }
            set {
                this["OPROnOff_DAQPinMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line23")]
        public string DAM1_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM1_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM1_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line24")]
        public string DAM2_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM2_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM2_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line25")]
        public string DAM3_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM3_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM3_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line26")]
        public string DAM4_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM4_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM4_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line27")]
        public string DAM5_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM5_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM5_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line28")]
        public string DAM6_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM6_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM6_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line29")]
        public string DAM7_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM7_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM7_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line30")]
        public string DAM8_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM8_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM8_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line31")]
        public string DAM9_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM9_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM9_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port1/line4")]
        public string DAM10_RelayCardNumberDAQPinName {
            get {
                return ((string)(this["DAM10_RelayCardNumberDAQPinName"]));
            }
            set {
                this["DAM10_RelayCardNumberDAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line1,{1}")]
        public string NormalModeCh1_DAQPinName {
            get {
                return ((string)(this["NormalModeCh1_DAQPinName"]));
            }
            set {
                this["NormalModeCh1_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line2,{1}")]
        public string NormalModeCh2_DAQPinName {
            get {
                return ((string)(this["NormalModeCh2_DAQPinName"]));
            }
            set {
                this["NormalModeCh2_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line3,{1}")]
        public string NormalModeCh3_DAQPinName {
            get {
                return ((string)(this["NormalModeCh3_DAQPinName"]));
            }
            set {
                this["NormalModeCh3_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line4,{1}")]
        public string NormalModeCh4_DAQPinName {
            get {
                return ((string)(this["NormalModeCh4_DAQPinName"]));
            }
            set {
                this["NormalModeCh4_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line5,{1}")]
        public string NormalModeCh5_DAQPinName {
            get {
                return ((string)(this["NormalModeCh5_DAQPinName"]));
            }
            set {
                this["NormalModeCh5_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line6,{1}")]
        public string NormalModeCh6_DAQPinName {
            get {
                return ((string)(this["NormalModeCh6_DAQPinName"]));
            }
            set {
                this["NormalModeCh6_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line7,{1}")]
        public string NormalModeCh7_DAQPinName {
            get {
                return ((string)(this["NormalModeCh7_DAQPinName"]));
            }
            set {
                this["NormalModeCh7_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line8,{1}")]
        public string NormalModeCh8_DAQPinName {
            get {
                return ((string)(this["NormalModeCh8_DAQPinName"]));
            }
            set {
                this["NormalModeCh8_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line9,{1}")]
        public string NormalModeCh9_DAQPinName {
            get {
                return ((string)(this["NormalModeCh9_DAQPinName"]));
            }
            set {
                this["NormalModeCh9_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line10,{1}")]
        public string NormalModeCh10_DAQPinName {
            get {
                return ((string)(this["NormalModeCh10_DAQPinName"]));
            }
            set {
                this["NormalModeCh10_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line11,{1}")]
        public string NormalModeCh11_DAQPinName {
            get {
                return ((string)(this["NormalModeCh11_DAQPinName"]));
            }
            set {
                this["NormalModeCh11_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line12,{1}")]
        public string NormalModeCh12_DAQPinName {
            get {
                return ((string)(this["NormalModeCh12_DAQPinName"]));
            }
            set {
                this["NormalModeCh12_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line13,{1}")]
        public string NormalModeCh13_DAQPinName {
            get {
                return ((string)(this["NormalModeCh13_DAQPinName"]));
            }
            set {
                this["NormalModeCh13_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line14,{1}")]
        public string NormalModeCh14_DAQPinName {
            get {
                return ((string)(this["NormalModeCh14_DAQPinName"]));
            }
            set {
                this["NormalModeCh14_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line15,{1}")]
        public string NormalModeCh15_DAQPinName {
            get {
                return ((string)(this["NormalModeCh15_DAQPinName"]));
            }
            set {
                this["NormalModeCh15_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line16,{1}")]
        public string NormalModeCh16_DAQPinName {
            get {
                return ((string)(this["NormalModeCh16_DAQPinName"]));
            }
            set {
                this["NormalModeCh16_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line17,{1}")]
        public string NormalModeCh17_DAQPinName {
            get {
                return ((string)(this["NormalModeCh17_DAQPinName"]));
            }
            set {
                this["NormalModeCh17_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line18,{1}")]
        public string NormalModeCh18_DAQPinName {
            get {
                return ((string)(this["NormalModeCh18_DAQPinName"]));
            }
            set {
                this["NormalModeCh18_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line19,{1}")]
        public string NormalModeCh19_DAQPinName {
            get {
                return ((string)(this["NormalModeCh19_DAQPinName"]));
            }
            set {
                this["NormalModeCh19_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line20,{1}")]
        public string NormalModeCh20_DAQPinName {
            get {
                return ((string)(this["NormalModeCh20_DAQPinName"]));
            }
            set {
                this["NormalModeCh20_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line21,{1}")]
        public string NormalModeCh21_DAQPinName {
            get {
                return ((string)(this["NormalModeCh21_DAQPinName"]));
            }
            set {
                this["NormalModeCh21_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line1,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh1_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh1_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh1_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line2,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh2_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh2_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh2_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line3,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh3_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh3_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh3_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line4,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh4_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh4_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh4_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line5,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh5_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh5_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh5_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line6,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh6_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh6_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh6_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line7,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh7_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh7_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh7_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line8,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh8_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh8_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh8_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line9,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh9_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh9_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh9_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line10,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh10_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh10_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh10_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line11,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh11_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh11_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh11_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line12,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh12_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh12_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh12_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line13,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh13_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh13_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh13_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line14,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh14_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh14_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh14_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line15,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh15_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh15_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh15_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line16,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh16_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh16_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh16_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line17,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh17_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh17_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh17_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line18,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh18_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh18_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh18_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line19,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh19_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh19_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh19_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line20,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh20_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh20_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh20_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port0/line21,{1},{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string WheatstoneModeCh21_DAQPinName {
            get {
                return ((string)(this["WheatstoneModeCh21_DAQPinName"]));
            }
            set {
                this["WheatstoneModeCh21_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port1/line1")]
        public string SelfTestNormalMode_DAQPinName {
            get {
                return ((string)(this["SelfTestNormalMode_DAQPinName"]));
            }
            set {
                this["SelfTestNormalMode_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/port1/line1,{0}/port1/line0,{0}/port1/line2,{0}/port1/line3")]
        public string SelfTestWheatstoneMode_DAQPinName {
            get {
                return ((string)(this["SelfTestWheatstoneMode_DAQPinName"]));
            }
            set {
                this["SelfTestWheatstoneMode_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/ai0")]
        public string WheatstoneAIChannel_DAQPinName {
            get {
                return ((string)(this["WheatstoneAIChannel_DAQPinName"]));
            }
            set {
                this["WheatstoneAIChannel_DAQPinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 1")]
        public string RCSNormalMode_SelectDAMRelay1 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay1"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 2")]
        public string RCSNormalMode_SelectDAMRelay2 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay2"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 3")]
        public string RCSNormalMode_SelectDAMRelay3 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay3"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 4")]
        public string RCSNormalMode_SelectDAMRelay4 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay4"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 5")]
        public string RCSNormalMode_SelectDAMRelay5 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay5"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 6")]
        public string RCSNormalMode_SelectDAMRelay6 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay6"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 7")]
        public string RCSNormalMode_SelectDAMRelay7 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay7"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 8")]
        public string RCSNormalMode_SelectDAMRelay8 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay8"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 9")]
        public string RCSNormalMode_SelectDAMRelay9 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay9"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 10")]
        public string RCSNormalMode_SelectDAMRelay10 {
            get {
                return ((string)(this["RCSNormalMode_SelectDAMRelay10"]));
            }
            set {
                this["RCSNormalMode_SelectDAMRelay10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 1")]
        public string RCSWheatstoneMode_SelectDAMRelay1 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay1"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 2")]
        public string RCSWheatstoneMode_SelectDAMRelay2 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay2"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 3")]
        public string RCSWheatstoneMode_SelectDAMRelay3 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay3"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 4")]
        public string RCSWheatstoneMode_SelectDAMRelay4 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay4"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 5")]
        public string RCSWheatstoneMode_SelectDAMRelay5 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay5"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 6")]
        public string RCSWheatstoneMode_SelectDAMRelay6 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay6"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 7")]
        public string RCSWheatstoneMode_SelectDAMRelay7 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay7"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 8")]
        public string RCSWheatstoneMode_SelectDAMRelay8 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay8"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 9")]
        public string RCSWheatstoneMode_SelectDAMRelay9 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay9"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 10")]
        public string RCSWheatstoneMode_SelectDAMRelay10 {
            get {
                return ((string)(this["RCSWheatstoneMode_SelectDAMRelay10"]));
            }
            set {
                this["RCSWheatstoneMode_SelectDAMRelay10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 1")]
        public string DRPINormalMode_SelectDAMRelay1 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay1"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 2")]
        public string DRPINormalMode_SelectDAMRelay2 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay2"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 3")]
        public string DRPINormalMode_SelectDAMRelay3 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay3"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 4")]
        public string DRPINormalMode_SelectDAMRelay4 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay4"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 5")]
        public string DRPINormalMode_SelectDAMRelay5 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay5"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 6")]
        public string DRPINormalMode_SelectDAMRelay6 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay6"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 7")]
        public string DRPINormalMode_SelectDAMRelay7 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay7"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 8")]
        public string DRPINormalMode_SelectDAMRelay8 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay8"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 9")]
        public string DRPINormalMode_SelectDAMRelay9 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay9"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 10")]
        public string DRPINormalMode_SelectDAMRelay10 {
            get {
                return ((string)(this["DRPINormalMode_SelectDAMRelay10"]));
            }
            set {
                this["DRPINormalMode_SelectDAMRelay10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 1")]
        public string DRPIWheatstoneMode_SelectDAMRelay1 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay1"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 2")]
        public string DRPIWheatstoneMode_SelectDAMRelay2 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay2"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 3")]
        public string DRPIWheatstoneMode_SelectDAMRelay3 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay3"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 4")]
        public string DRPIWheatstoneMode_SelectDAMRelay4 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay4"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 5")]
        public string DRPIWheatstoneMode_SelectDAMRelay5 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay5"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 6")]
        public string DRPIWheatstoneMode_SelectDAMRelay6 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay6"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 7")]
        public string DRPIWheatstoneMode_SelectDAMRelay7 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay7"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 8")]
        public string DRPIWheatstoneMode_SelectDAMRelay8 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay8"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 9")]
        public string DRPIWheatstoneMode_SelectDAMRelay9 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay9"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DAM 10")]
        public string DRPIWheatstoneMode_SelectDAMRelay10 {
            get {
                return ((string)(this["DRPIWheatstoneMode_SelectDAMRelay10"]));
            }
            set {
                this["DRPIWheatstoneMode_SelectDAMRelay10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.0")]
        public decimal WheatstoneMode_Calculate1 {
            get {
                return ((decimal)(this["WheatstoneMode_Calculate1"]));
            }
            set {
                this["WheatstoneMode_Calculate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0")]
        public decimal WheatstoneMode_Calculate2 {
            get {
                return ((decimal)(this["WheatstoneMode_Calculate2"]));
            }
            set {
                this["WheatstoneMode_Calculate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public decimal WheatstoneMode_Calculate3 {
            get {
                return ((decimal)(this["WheatstoneMode_Calculate3"]));
            }
            set {
                this["WheatstoneMode_Calculate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public decimal WheatstoneMode_Compensation {
            get {
                return ((decimal)(this["WheatstoneMode_Compensation"]));
            }
            set {
                this["WheatstoneMode_Compensation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessDBFileName {
            get {
                return ((string)(this["AccessDBFileName"]));
            }
            set {
                this["AccessDBFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessDBMaxOhDegree {
            get {
                return ((string)(this["AccessDBMaxOhDegree"]));
            }
            set {
                this["AccessDBMaxOhDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePathSetting {
            get {
                return ((string)(this["FilePathSetting"]));
            }
            set {
                this["FilePathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MeasurementType {
            get {
                return ((int)(this["MeasurementType"]));
            }
            set {
                this["MeasurementType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectDRPI_Hogi {
            get {
                return ((string)(this["SelectDRPI_Hogi"]));
            }
            set {
                this["SelectDRPI_Hogi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectDRPI_OHDegree {
            get {
                return ((string)(this["SelectDRPI_OHDegree"]));
            }
            set {
                this["SelectDRPI_OHDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectRCS_Hogi {
            get {
                return ((string)(this["SelectRCS_Hogi"]));
            }
            set {
                this["SelectRCS_Hogi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectRCS_OHDegree {
            get {
                return ((string)(this["SelectRCS_OHDegree"]));
            }
            set {
                this["SelectRCS_OHDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectDRPI_TDRHogi {
            get {
                return ((string)(this["SelectDRPI_TDRHogi"]));
            }
            set {
                this["SelectDRPI_TDRHogi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectDRPI_TDROHDegree {
            get {
                return ((string)(this["SelectDRPI_TDROHDegree"]));
            }
            set {
                this["SelectDRPI_TDROHDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectRCS_TDRHogi {
            get {
                return ((string)(this["SelectRCS_TDRHogi"]));
            }
            set {
                this["SelectRCS_TDRHogi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectRCS_TDROHDegree {
            get {
                return ((string)(this["SelectRCS_TDROHDegree"]));
            }
            set {
                this["SelectRCS_TDROHDegree"] = value;
            }
        }
    }
}
